package fr.acceis.forum.classe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

public class JeuDeTestJdBc {
	public static Connection connection;
	
	public final static String[] QUERIES = {
			"drop table Messages if exists",
			"drop table Threads if exists",
			"drop table Description if exists",
			"drop table Utilisateurs if exists",
			
			"create table Utilisateurs ("
			+ "id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null, "
			+ "login varchar(255) not null, "
			+ "password varchar(255) not null, "
			+ "PRIMARY KEY(login)"
			+ ")",
			
			"create table Threads ("
			+ "id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1)  not null, "
			+ "sujet varchar(255), "
			+ "auteur varchar(255) not null, "
			+ "reponse int, "
			+ "vues int, "
			+ "PRIMARY KEY(id), "
			+ "FOREIGN KEY(auteur) REFERENCES Utilisateurs(login)"
			+ ")",
			
			"create table Messages ("
			+ "id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null, "
			+ "id_discussion bigint not null, "
			+ "auteur varchar(255), "
			+ "texte varchar(4096), "
			+ "PRIMARY KEY (id), "
			+ "FOREIGN KEY (id_discussion) REFERENCES Threads(id)"
			+ ")",
			
			"create table Description ("
			+ "id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null, "
			+ "pseudo varchar(255), "
			+ "nom varchar(255), "
			+ "prenom varchar(255), "
			+ "age int, "
			+ "description varchar(4096), "
			+ "PRIMARY KEY (id), "
			+ "FOREIGN KEY (pseudo) REFERENCES Utilisateurs(login)"
			+ ")",
			
			
			"INSERT INTO Utilisateurs (login, password) VALUES('admin', 'admin')",
			"INSERT INTO Utilisateurs (login, password) VALUES('pierre', 'pierre')",
			"INSERT INTO Utilisateurs (login, password) VALUES('jose', 'jose')",
			"INSERT INTO Utilisateurs (login, password) VALUES('paul', 'paul')",
			"INSERT INTO Utilisateurs (login, password) VALUES('jacques', 'jacques')",
			
			"INSERT INTO Threads (sujet, auteur, reponse, vues) VALUES('SUJET IMPORTANT', 'admin', 0, 4242)",
			"INSERT INTO Threads (sujet, auteur, reponse, vues) VALUES('Sujet n°2', 'pierre', 0, 150)",
			
			"INSERT INTO Messages (id_discussion, auteur, texte) VALUES(1, 'admin', 'Message Test')",
			"INSERT INTO Messages (id_discussion, auteur, texte) VALUES(2, 'pierre', 'Message test aussi')"
	};

	public static Connection getConnection() throws Exception {
		if (connection == null) {
			Class.forName("org.hsqldb.jdbcDriver").newInstance();
			connection = DriverManager.getConnection("jdbc:hsqldb:/home/dorian/Cours/TP/GLA/GLA_project/ForumGLA/forum/data/basejpa", "sa",  "");
			Statement stmt = connection.createStatement();
	
			for (String query : QUERIES) {
				stmt.executeUpdate(query);
			}
		}
		return connection;

	}

}
